version: '3'

services:
  etcd:
    container_name: contrail_patroni_etcd
    image: patroni
    command: --etcd

  haproxy:
    container_name: contrail_haproxy
    image: patroni
    ports:
      - "5432:5000"
      - "5001:5001"
    environment:
      PATRONI_ETCD_URL: http://$ETCDIP:2379
      PATRONI_SCOPE: testcluster
    command: --confd
    volumes:
      - haproxy_db:/var/lib/postgresql/data

  dbnode:
    image: patroni
    volumes:
      - ./patroni.yml:/patroni.yml:ro
      - ../../tools:/tools
      - patroni_dbnode:/var/lib/postgresql/data
    environment:
      PATRONI_ETCD_URL: http://$ETCDIP:2379
      PATRONI_SCOPE: testcluster
      PATRONI_SUPERUSER_USERNAME: root
      PATRONI_SUPERUSER_PASSWORD: contrail123

networks:
  default:
    external:
      name: $NETWORKNAME

volumes:
  haproxy_db:
  patroni_dbnode:
